---
# The production version contains the limited text.  We'll just test for "Freddie Lochner" This version of the website
# should be available on port 8080 of your server.
- name: Deploy the production version of your website based on the previous tag of your docker-cloud-test image
  hosts: localhost
  become: true
  vars:
    unh698_environment: production
    unh698_image_version: release-0.0.2
    unh698_host_port: 8080
    unh698_container_port: 5000
  roles:
    - projectWeb
  