---
# This staging version of the website should be available on port 8081 of your server.
- name: Deploy the staging version of your website based on the newest tag of your projectWeb image
  hosts: localhost
  become: true
  vars:
    projectWeb_environment: staging
    projectWeb_image_version: release-0.1.0
    projectWeb_host_port: 8081
    projectWeb_container_port: 5000
  roles:
    - projectWeb
  