---
# This staging version of the website should be available on port 8081 of your server.
- name: Deploy the staging version of your website based on the newest tag of your projectWeb image
  hosts: localhost
  become: true
  vars:
    unh698_environment: staging
    unh698_image_version: release-0.0.4
    unh698_host_port: 8081
    unh698_container_port: 5000
  roles:
    - projectWeb
  